### ISSUE TITLE
Zadost o radu

### ISSUE THREAD

**Issue by JStika** [nepada/meta-control#1]
Jak to muzu nainstalovat?

Po vykonani composer require nepada/meta-control
dostavam: 
[InvalidArgumentException]
Package nepada/meta-control at version  has a PHP requirement incompatible with your PHP version (5.6)

muj composer.json:
{
	"name": "nette/sandbox",
	"description": "The sandbox is a pre-packaged Nette Framework project, basic configured structure for your application.",
	"homepage": "https://nette.org",
	"type": "project",
	"license": ["BSD-3-Clause", "GPL-2.0", "GPL-3.0"],
	"authors": [
		{
			"name": "David Grudl",
			"homepage": "https://davidgrudl.com"
		},
		{
			"name": "Nette Community",
			"homepage": "https://nette.org/contributors"
		}
	],
	"require": {
		"php": ">=5.6.0",
		"nette/application": "^2.4.4",
		"nette/bootstrap": "^2.4.3",
		"nette/caching": "^2.5",
		"nette/database": "^2.4",
		"nette/di": "^2.4",
		"nette/finder": "^2.4",
		"nette/forms": "^2.4",
		"nette/http": "^2.4",
		"nette/mail": "^2.4",
		"nette/robot-loader": "^2.4 || ^3.0",
		"nette/safe-stream": "^2.3",
		"nette/security": "^2.4",
		"nette/utils": "^2.4",
		"latte/latte": "^2.4",
		"tracy/tracy": "^2.4",
		"dg/adminer-custom": "^1.9",
		"contributte/recaptcha": "^3.1",
		"janmarek/webloader": "^2.5",
		"joseki/webloader-filters": "^1.1",
		"oyejorge/less.php": "v1.7.0.14",
		"leafo/scssphp": "^0.8.2",
		"nextras/mail-panel": "^2.4"
	},
	"require-dev": {
		"nette/tester": "^2.0"
	},
	"minimum-stability": "stable",
	"config": {
		"platform": {
			"php": "5.6"
		}
	}
}

**Comment by xificurk** [comment]
PHP 5.6 není podporováno. PHP 5.6 je již několik let bez aktivní podpory a téměř rok dokonce bez bezpečnostních updatů, viz https://www.php.net/supported-versions.php
